CREATE TABLE usuarios (
    id INT PRIMARY KEY AUTO_INCREMENT,
    nome_usuario VARCHAR(255) NOT NULL,
    senha_hash VARCHAR(255) NOT NULL,
    ip VARCHAR(45)
);

CREATE TABLE denuncias (
    id INT PRIMARY KEY AUTO_INCREMENT,
    nome VARCHAR(255) NULL,
    telefone VARCHAR(20) NULL,
    cpf VARCHAR(20) NULL,
    mensagem TEXT NOT NULL,
    data_hora DATETIME DEFAULT CURRENT_TIMESTAMP,
    ip VARCHAR(45)
);